# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=10)),
                ('category', models.IntegerField()),
                ('tags', models.CharField(max_length=30)),
                ('visibility', models.BooleanField(default=True)),
                ('keywords', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('titlepic', models.ImageField(null=True, upload_to='article')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truename', models.CharField(max_length=10, null=True)),
                ('usertel', models.CharField(max_length=13, null=True)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
