# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
